version: '3'

services:
  utils:
    container_name: utils
    image: dev-notification-utils
    build:
      context: .
      dockerfile: devcontainer-utils/Dockerfile
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    restart: always
