name: Run daily scans

on:
  schedule:
    # cron format: 'minute hour dayofmonth month dayofweek'
    # this will run at noon UTC every day (7am EST / 8am EDT)
    - cron: '0 12 * * *'

permissions:
  contents: read

jobs:
  pip-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-project
      - name: Create requirements.txt
        run: poetry export --without-hashes --format=requirements.txt > requirements.txt
      - uses: pypa/gh-action-pip-audit@v1.0.6
        with:
          inputs: requirements.txt
      - name: Upload pip-audit artifact
        uses: actions/upload-artifact@v3
        with:
          name: pip-audit-report
          path: /tmp/pip-audit-output.txt

  static-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-project
      - name: Install bandit
        run: pip install bandit
      - name: Run scan
        run: bandit -r app/ -f txt -o /tmp/bandit-output.txt --confidence-level medium
      - name: Upload bandit artifact
        uses: actions/upload-artifact@v3
        with:
          name: bandit-report
          path: /tmp/bandit-output.txt
